/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code06;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LinkedList newLIST=new LinkedList();
        newLIST.append(3);
    }
}
