/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code10;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//        Stack<String> newObject=new Stack<>();
//        newObject.push("m");
//        newObject.push("o");
//        System.out.println(newObject.top.nodeValue);
        Stack<String> newobj=new Stack<>();
        System.out.println(newobj.isEmty());
        newobj.push("H");
        newobj.push("m");
        newobj.push("n");
       ///Arrays.toString(newobj.toArray());
       // for() System.out.println( + "");
       System.out.println(newobj.top.nodeValue);
       // System.out.println(newobj.isEmty());
       newobj.pop();
        System.out.println(newobj.peek());
        //System.out.println(newobj.print());
        System.out.println(newobj.isEmty());

       // System.out.println(newobj.top.nodeValue);
//        try {
//            System.out.println(newobj.pop());
//            System.out.println(newobj.top.nodeValue);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        Queue<String> newobj2=new Queue<>();
        System.out.println(newobj2.isEmty());
        newobj2.enqueue("H");
        newobj2.enqueue("m");
        newobj2.enqueue("d");
        ///Arrays.toString(newobj.toArray());
        // for() System.out.println( + "");
        //System.out.println(newobj2.front.nodeValue);
        //System.out.println(newobj2.rear.nodeValue);
        // System.out.println(newobj.isEmty());
        newobj2.dequeue();
        System.out.println(newobj2.peek());
       // System.out.println(newobj2.print());
        System.out.println(newobj2.isEmty());

    }
}
