/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LinkedList newList = new LinkedList();
        newList.insert(3);
        newList.insert(1);
        //newList.toString();
        //newList.append(5);
        newList.insertAfter(1,4);
        newList.insertbefore(3,0);
       newList.append(7);
        //System.out.println(newList.linkedlistkth(1));
      //newList.print(newList.head);//to show node
        //System.out.println(newList.includes(3));
       //newList.append(11);
        LinkedList list1=new LinkedList();
        list1.insert(1);
        list1.insert(2);
        list1.insert(3);
        LinkedList list2=new LinkedList();
        list2.insert(4);
        list2.insert(5);
        list2.insert(6);
        LinkedList list3=new LinkedList();
       // list1.toString();
       // list2.toString();
        ;
       // System.out.println(list3.zip(list2,list1));

      //System.out.println(LinkedList.reverseList(list1).toString());
       // System.out.println(reversedLinkedList(list2).toString());
        //reversedLinkedList(list1).to
        LinkedList list4 = new LinkedList();
        list4.append(1);
        list4.append(2);
        list4.append(3);
       // System.out.println(LinkedList.reversedLinkedList(list4).toString());


        //list2.insertAfter(5,2);
        //list2.insertbefore(6,3);
        //System.out.println(list2.includes(5));
        System.out.println(list2.toString());
       System.out.println((list2.linkedlistkth(3)));
//        LinkedList newtest=new LinkedList();
//        newtest.append(4);
//        newtest.append(5);
//        newtest.append(7);
//        newtest.insertAfter(5,2);
//        System.out.println(newtest.toString());
        ////
//        LinkedList list44 = new LinkedList();
//        list44.append(1);
//        list44.append(2);
//        list44.append(3);
//        LinkedList list55 = new LinkedList();
//        list55.append(11);
//        list55.append(22);
//        list55.append(33);
//        LinkedList listmerage = new LinkedList();
//        System.out.println(listmerage.zip(list44,list55));
    }
}
